---
- import_playbook: "{{ '$SHARE_DIR/playbooks/infrastructure/buster-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/infrastructure/network-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/firewall/firewall-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/wazuh/wazuh-firewall-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/misc/sexy-debian-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/misc/sshd-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/bind/bind-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/bind/bind-client-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/bind/bind-dhcp-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/authorized_keys/authorized-keys-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/backup/backup-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/icinga/icinga-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/icinga/monitor-external-ressources-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/bind/bind-monitoring-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/postfix/postfix-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/wazuh/wazuh-manager-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/wazuh/wazuh-agent-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/weblate/weblate-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/gitlab/gitlab-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/gitlab/gitlab-ci-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/packages/packages-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/packages/enough-android-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/chat/chat-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/cloud/cloud-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/enough/enough-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/website/website-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/forum/forum-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/api/api-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/openvpn/openvpn-server-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/openvpn/openvpn-client-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/misc/uninstall-ntp.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/misc/fail2ban-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/misc/upgrades-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/misc/commit_etc-playbook.yml' | expandvars }}"
