[tool.poetry]
name = "keios-zmq"
version = "1.3.0"
description = ""
authors = ["Leftshift One <contact@leftshift.one>"]

[tool.poetry.dependencies]
python = "^3.8"
pyzmq = "^18.0"
aiozmq = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-cov = "^2.8.1"
toml = "^0.10.0"
pytest-asyncio = "^0.12.0"

[tool.poetry.scripts]
install = "poetry_scripts:install"
test = "poetry_scripts:test"
build = "poetry_scripts:build"
publish = "poetry_scripts:publish"
release = "poetry_scripts:release" # e.g. poetry run release minor

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"