[tool.poetry]
name = "kharser"
version = "0.1.1"
description = "parse stuff"
authors = ["KhalidCK <fr.ckhalid@gmail.com>"]
readme = 'readme.md'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.770"
isort = "^4.3.21"
tox = "^3.15.1"
pytest-datadir = "^1.3.1"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
