[tool.poetry]
name = "stonks-trader"
version = "0.1.4-alpha"
description = ""
authors = ["glyphack <sh.hooshyari@gmail.com>"]

[tool.poetry.scripts]
stonks-trader = "stonks_trader.cli.cli_app:app"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "*"
pandas = "*"
typer = "*"
pytse_client = "*"
matplotlib = "*"
ta = "*"
requests = "*"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
