[tool.poetry]
name = "jedi_toolz"
version = "0.0.21"
description = "A collection of utilities to simplify a data workflow using pandas, Excel, DOMO, and other tools."
authors = ["JediHero <hansen.rusty@gmail.com>"]
homepage = "https://github.com/JediHero/jedi_toolz"

[tool.poetry.dependencies]
python = ">=3.6.1"
tabulate = "^0.8.7"
openpyxl = "^3.0.3"
toolz = "^0.10.0"
pydomo = "^0.2.3"
decorator = "^4.4.2"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
jupyter = "^1.0.0"
pandas = "^1.0.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
