
[tool.poetry]
name = "RandoAlgo-rjay"
version = "0.1.1"
description = "A python package that gets random algorithm questions"
authors = ["Rashidat Jimoh"]
license = "MIT"
readme = 'README.md'
repository ='https://github.com/startng/forward--RandoAlgo-Rjay'
packages= [
    {include = './requestalgorithms.py'},
    {include= './README.md'},
    {include='./userplay.py'},
    
]

[tool.poetry.dependencies]
python = "^3"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
RandoAlgo='userplay:userLogin'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
