[tool.poetry]
name = "aithermal"
version = "0.2.6"
description = ""
authors = ["mjaquier <mjaquier@me.com>"]

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^5.3.1"
pandas = "^1.0.3"
xlsxwriter = "^1.2.8"
simplelogging = "^0.10.0"
oyaml = "^0.9"
aihelper = "^0.1.9"
scipy = "^1.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
