[tool.poetry]
name = "until"
version = "0.1.0"
description = ""
authors = ["Rafael de Oliveira Marques <rafaelomarques@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
coverage = "^5.0.3"
flake8 = "^3.8.2"
mock = "^4.0.2"
pylint = "^2.5.2"
pytest = "^5.2"
pytest-cov = "^2.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
