[tool.poetry]
name = "khadoop"
version = "0.1.0"
description = ""
authors = ["Khalid <khalidck@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
mypy = "^0.770"
tox = "^3.15.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.2"
autopep8 = "^1.5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
