[tool.poetry]

name = "decorated_registry"
version = "0.0.2"
description = "Decorator-based registry for objects with arbitrary payloads"
authors = [
    "Andrey Cizov <acizov@gmail.com>"
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/andreycizov/python-decorated_registry"
repository = "https://github.com/andreycizov/python-decorated_registry"
documentation = "https://github.com/andreycizov/python-decorated_registry"

keywords = ["registry", "decorator", "generic", "register"]

classifiers = [
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Natural Language :: English',
        'Programming Language :: Python :: 3.6',
]

# Requirements
[tool.poetry.dependencies]
python = "^3.6"
dataclasses = { version = ">0.1", python = "<3.7" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
